//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class ATCCodes
    {
        [Key]
        public int ATCCodeID { get; set; }

        //public string Code { get; set; }
        public string CodeDescription { get; set; }
        public string SubcodeDescription { get; set; }
        public string SubCode { get; set; }
        public string ATCCode { get; set; }
        public string DrugName { get; set; }
        public string Purpose { get; set; }
        public string DrugDescription { get; set; }
        public DateTime? CodeEffectiveFrom { get; set; }
        public DateTime? CodeEffectiveTill { get; set; }
        public bool IsActive { get; set; }
        public long? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CodeTableNumber { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}
