//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class AuditLog
    {
        public AuditLog()
        {
            this.AuditLogArchived = new HashSet<AuditLogArchived>();
            this.AuditLogArchived1 = new HashSet<AuditLogArchived>();
        }
        [Key]
        public int AuditLogID { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> PrimaryKey { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string EventType { get; set; }
        public string ExtValue1 { get; set; }
        public string ExtValue2 { get; set; }
        public string ExtValue3 { get; set; }

        [ScriptIgnoreAttribute]
        public virtual Users Users { get; set; }

        public virtual ICollection<AuditLogArchived> AuditLogArchived { get; set; }
        public virtual ICollection<AuditLogArchived> AuditLogArchived1 { get; set; }
    }
}
