//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorizations
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string EncounterPatientID { get; set; }
        public string EncounterID { get; set; }
        public Nullable<System.DateTime> AuthorizationDateOrdered { get; set; }
        public Nullable<System.DateTime> AuthorizationStart { get; set; }
        public Nullable<System.DateTime> AuthorizationEnd { get; set; }
        public string AuthorizationID { get; set; }
        public string AuthorizationType { get; set; }
        public string AuthorizationComments { get; set; }
        public Nullable<int> AuthorizationDenialCode { get; set; }
        public string AuthorizationIDPayer { get; set; }
        public Nullable<decimal> AuthorizationLimit { get; set; }
        public string AuthorizationMemberID { get; set; }
        public Nullable<int> AuthorizationResult { get; set; }
        public Nullable<int> PatientId { get; set; }
    }
}
