//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedCharges
    {
        [Key]
        public int BedChargesID { get; set; }
        public Nullable<int> BCCorporateID { get; set; }
        public Nullable<int> BCFacilityID { get; set; }
        public Nullable<int> BCPatientID { get; set; }
        public Nullable<int> BCEncounterID { get; set; }
        public Nullable<int> BCBedID { get; set; }
        public Nullable<int> BCMappingBedPatientID { get; set; }
        public Nullable<int> BCRangeStart { get; set; }
        public Nullable<int> BCRangeEnd { get; set; }
        public Nullable<int> BCBedRateTypeID { get; set; }
        public Nullable<System.DateTime> BCTransactionDate { get; set; }
        public Nullable<int> BCRangeEffectiveDays { get; set; }
        public Nullable<decimal> BCUnitRate { get; set; }
        public Nullable<decimal> BCGross { get; set; }
        public Nullable<System.DateTime> BCActivityStartDate { get; set; }
        public Nullable<System.DateTime> BCActivityEndDate { get; set; }
        public Nullable<int> BCTotalEffectiveDays { get; set; }
        public string BCStatus { get; set; }
        public Nullable<int> BCCreatedBy { get; set; }
        public Nullable<System.DateTime> BCCreatedDate { get; set; }
        public Nullable<int> BCModifiedBy { get; set; }
        public Nullable<System.DateTime> BCModifiedDate { get; set; }
        public Nullable<bool> BCIsActive { get; set; }
        public string ServiceCodeValue { get; set; }
    }
}
