//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class BedRateCard
    {
        [Key]
        public int BedRateCardID { get; set; }
        public Nullable<int> BedTypes { get; set; }
        public string UnitType { get; set; }
        public Nullable<decimal> Rates { get; set; }
        public Nullable<int> DayStart { get; set; }
        public Nullable<int> DayEnd { get; set; }
        public string ServiceCodeValue { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public DateTime? EffectiveFrom { get; set; }
        public DateTime? EffectiveTill { get; set; }
        public int? FacilityId { get; set; }
        public int? CorporateId { get; set; }
    }
}
