//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedTransaction
    {
        [Key]
        public int BedTransactionID { get; set; }
        public Nullable<int> MappingPatientBedID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> EncounterID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<int> BedType { get; set; }
        public Nullable<int> EffectiveDays { get; set; }
        public Nullable<System.DateTime> BedTransactionComputedOn { get; set; }
        public Nullable<int> ChargeUnit { get; set; }
        public Nullable<int> Transactionbracket { get; set; }
        public Nullable<decimal> BedCharges { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
        public string BillNumber { get; set; }
        public Nullable<int> BillStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CorporateID { get; set; }
    }
}
