//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Country
    {
        public Country()
        {
            this.CountryHoliday = new HashSet<CountryHoliday>();
            this.State = new HashSet<State>();
            this.Facility = new HashSet<Facility>();
        }
        [Key]
        public int CountryID { get; set; }
        public string CodeValue { get; set; }
        public string CountryName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }

        public virtual ICollection<CountryHoliday> CountryHoliday { get; set; }
        public virtual ICollection<State> State { get; set; }
        public virtual ICollection<Facility> Facility { get; set; }
    }
}
