//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTransactionCounter
    {
        [Key]
        public int CounterId { get; set; }
        public Nullable<int> StatisticDescription { get; set; }
        public Nullable<System.DateTime> ActivityDay { get; set; }
        public Nullable<decimal> ActivityTotal { get; set; }
        public Nullable<decimal> DepartmentNumber { get; set; }
        public int CorporateId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
