//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardRemark
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> DashboardType { get; set; }
        public string DashboardSection { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Month { get; set; }
        public string ExternalValue1 { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
