//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardDisplayOrder
    {
        [Key]
        public int Id { get; set; }
        public string DashboardId { get; set; }
        public string SectionId { get; set; }
        public string IndicatorNumber { get; set; }
        public string SubCategory1 { get; set; }
        public string SubCategory2 { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public int SortOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
