//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardParameters
    {
        [Key]
        public int ParameterId { get; set; }
        public string DashboardType { get; set; }
        public string IndicatorCategory { get; set; }
        public string DataField { get; set; }
        public string ValueType { get; set; }
        public string Argument { get; set; }
        public string RangeFrom { get; set; }
        public string RangeTo { get; set; }
        public string ColorCode { get; set; }
        public int FacilityId { get; set; }
        public int CorporateId { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
        public string ExternalValue3 { get; set; }
        public string ExternalValue4 { get; set; }
        public string ExternalValue5 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
