//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardIndicatorData_Template
    {
        [Key]
        public int ID { get; set; }
        public Nullable<int> IndicatorId { get; set; }
        public string IndicatorNumber { get; set; }
        public string SubCategory1 { get; set; }
        public string SubCategory2 { get; set; }
        public string StatisticData { get; set; }
        public Nullable<int> Month { get; set; }
        public string Year { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
        public string ExternalValue3 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DepartmentNumber { get; set; }
    }
}
