//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTargets
    {
        [Key]
        public int TargetId { get; set; }
        public string TargetDescription { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UnitOfMeasure { get; set; }
        public Nullable<int> TimingIncrement { get; set; }
        public Nullable<decimal> Target { get; set; }
        public int CorporateId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
