//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardBudget
    {
        [Key]
        public int BudgetId { get; set; }
        public Nullable<int> BudgetType { get; set; }
        public string BudgetDescription { get; set; }
        public Nullable<decimal> DepartmentNumber { get; set; }
        public string FiscalYear { get; set; }
        public Nullable<decimal> JanuaryBudget { get; set; }
        public Nullable<decimal> FebruaryBudget { get; set; }
        public Nullable<decimal> MarchBudget { get; set; }
        public Nullable<decimal> AprilBudget { get; set; }
        public Nullable<decimal> MayBudget { get; set; }
        public Nullable<decimal> JuneBudget { get; set; }
        public Nullable<decimal> JulyBudget { get; set; }
        public Nullable<decimal> AugustBudget { get; set; }
        public Nullable<decimal> SeptemberBudget { get; set; }
        public Nullable<decimal> OctoberBudget { get; set; }
        public Nullable<decimal> NovemberBudget { get; set; }
        public Nullable<decimal> DecemberBudget { get; set; }
        public int CorporateId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BudgetFor { get; set; }
    }
}
