//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        [Key]
        public int Id { get; set; }
        public string DrugTableNumber { get; set; }
        public string DrugDescription { get; set; }
        public string DrugCode { get; set; }
        public string DrugInsurancePlan { get; set; }
        public string DrugPackageName { get; set; }
        public string DrugGenericName { get; set; }
        public string DrugStrength { get; set; }
        public string DrugDosage { get; set; }
        public string DrugPackageSize { get; set; }
        public string DrugPricePublic { get; set; }
        public string DrugPricePharmacy { get; set; }
        public string DrugUnitPricePublic { get; set; }
        public string DrugUnitPricePharmacy { get; set; }
        public string DrugStatus { get; set; }
        public Nullable<System.DateTime> DrugDeleteDate { get; set; }
        public Nullable<System.DateTime> DrugLastChange { get; set; }
        public string DrugAgentName { get; set; }
        public string DrugManufacturer { get; set; }
        public string DrugStrengthHardcode { get; set; }
        public string DrugStrengthHardcodeUOM { get; set; }
        public string DrugPackagesizeHardcode { get; set; }
        public string DrugPackagesizeHardcodeUOM { get; set; }
        public string BrandCode { get; set; }
        public Nullable<bool> InStock { get; set; }
        public string ATCCode { get; set; }
    }
}
