//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugAllergyLog
    {
        [Key]
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public string OrderCategory { get; set; }
        public string OrderSubCategory { get; set; }
        public string OrderType { get; set; }
        public string OrderName { get; set; }
        public string AllergyType { get; set; }
        public string ReactionType { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> EncounterId { get; set; }
        public string ReactionOrderCode { get; set; }
        public string AllergyFromName { get; set; }
        public Nullable<bool> IsOrderCancel { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<System.DateTime> OrderStartDate { get; set; }
        public Nullable<System.DateTime> OrderEndDate { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
