//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EquipmentMaster
    {
        [Key]
        public int EquipmentMasterId { get; set; }
        public string FacilityId { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentType { get; set; }
        public string EquipmentModel { get; set; }
        public string EquipmentSerialNumber { get; set; }
        public Nullable<bool> EquipmentIsInsured { get; set; }
        public Nullable<System.DateTime> EquipmentAquistionDate { get; set; }
        public bool EquipmentDisabled { get; set; }
        public Nullable<System.DateTime> EquipmentDisabledDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsEquipmentFixed { get; set; }
        public string TurnAroundTime { get; set; }
        public string CorporateId { get; set; }
        public string BaseLocation { get; set; }
        public int FacilityStructureId { get; set; }
        public Nullable<System.DateTime> EquipmentEnableDate { get; set; }
    }
}
