//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorMaster
    {
        [Key]
        public int ErrorMasterID { get; set; }
        public Nullable<int> CorporateID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public string ErrorCode { get; set; }
        public Nullable<int> ErrorType { get; set; }
        public string ErrorDescription { get; set; }
        public string ErrorResolution { get; set; }
        public string ExtValue1 { get; set; }
        public string ExtValue2 { get; set; }
        public string ExtValue3 { get; set; }
        public string ExtValue4 { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
