//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityStructure
    {
        [Key]
        public int FacilityStructureId { get; set; }
        public Nullable<int> GlobalCodeID { get; set; }
        public string FacilityStructureValue { get; set; }
        public string FacilityStructureName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ParentTypeGlobalID { get; set; }
        public string FacilityId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
        public string ExternalValue3 { get; set; }
        public string ExternalValue4 { get; set; }
        public string ExternalValue5 { get; set; }

        public string DeptOpeningTime { get; set; }
        public string DeptClosingTime { get; set; }
        public string DeptOpeningDays { get; set; }
        public string DeptTurnaroundTime { get; set; }
        public string EquipmentIds { get; set; }
    }
}
