//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class FacilityRole
    {
        [Key]
        public int FacilityRoleId { get; set; }
        public int FacilityId { get; set; }
        public int RoleId { get; set; }
        public int CorporateId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public bool SchedulingApplied { get; set; }
        [ScriptIgnoreAttribute]
        public virtual Role Role { get; set; }

        public bool CarePlanAccessible { get; set; }
    }
}
