//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePolices
    {
        [Key]
        public int InsurancePolicyId { get; set; }

        [StringLength(100)]
        public string PlanName { get; set; }

        [StringLength(20)]
        public string PlanNumber { get; set; }

        [StringLength(100)]
        [Required]
        public string PolicyName { get; set; }

        [StringLength(20)]
        [Required]
        public string PolicyNumber { get; set; }

        public DateTime? PolicyBeginDate { get; set; }
        public DateTime? PolicyEndDate { get; set; }

        [StringLength(200)]
        public string PolicyDescription { get; set; }

        [StringLength(100)]
        public string PolicyHolderName { get; set; }

        public int InsuranceCompanyId { get; set; }

        [StringLength(15)]
        public string SocialSecurityNumber { get; set; }

        [StringLength(15)]
        public string McContractCode { get; set; }

        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int? DeletedBy { get; set; }
        public bool IsActive { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int InsurancePlanId { get; set; }

        public int FacilityId { get; set; }
        public int CorporateId { get; set; }
    }
}
