//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagedCare
    {
        [Key]
        public int ManagedCareID { get; set; }
        public Nullable<int> ManagedCareInsuranceID { get; set; }
        public Nullable<int> ManagedCarePlanID { get; set; }
        public Nullable<int> ManagedCarePolicyID { get; set; }
        public Nullable<decimal> ManagedCareMultiplier { get; set; }
        public Nullable<decimal> ManagedCareInpatientDeduct { get; set; }
        public Nullable<decimal> ManagedCareOutpatientDeduct { get; set; }
        public Nullable<decimal> ManagedCarePerDiems { get; set; }
        public Nullable<int> CorporateID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
