//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualChargesTracking
    {
        [Key]
        public int ManualChargesTrackingID { get; set; }
        public string TrackingType { get; set; }
        public string TrackingTypeNameVal { get; set; }
        public string TrackingColumnName { get; set; }
        public string TrackingTableName { get; set; }
        public string TrackingValue { get; set; }
        public string TrackingBillStatus { get; set; }
        public int BillHeaderID { get; set; }
        public int EncounterID { get; set; }
        public int PatientID { get; set; }
        public int FacilityID { get; set; }
        public int CorporateID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
        public string ExternalValue3 { get; set; }
        public string ExternalValue4 { get; set; }
        public string ExternalValue5 { get; set; }
        public string ExternalValue6 { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    }
}
