//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCContractTracking
    {
        [Key]
        public long MCContractTrackingID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> EncounterID { get; set; }
        public string MCOrderType { get; set; }
        public string MCOrderCode { get; set; }
        public Nullable<int> PolicyID { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<System.DateTime> PolicyEndDate { get; set; }
        public Nullable<int> MCContractID { get; set; }
        public string MCContractCode { get; set; }
        public string MCLevel { get; set; }
        public string MCEncounterType { get; set; }
        public Nullable<int> MCPatientPercent { get; set; }
        public Nullable<int> MCPatientFixed { get; set; }
        public Nullable<int> MCPatientCapping { get; set; }
        public Nullable<int> MCMultiplier { get; set; }
        public Nullable<decimal> AlreadyAppliedPatientShare { get; set; }
        public Nullable<decimal> GrossAfterMultiplier { get; set; }
        public Nullable<decimal> PatientShare { get; set; }
        public Nullable<decimal> PayerNET { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BCCreatedBy { get; set; }
        public Nullable<System.DateTime> BCCreatedDate { get; set; }
        public Nullable<int> BCModifiedBy { get; set; }
        public Nullable<System.DateTime> BCModifiedDate { get; set; }
        public Nullable<bool> BCIsActive { get; set; }
    }
}
