//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCOrderCodeRates
    {
        [Key]
        public int MCOrderCodeRatesId { get; set; }
        public Nullable<int> MCCode { get; set; }
        public string OrderCodeRatTableNumber { get; set; }
        public string OrderCodeRateTableName { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string OrderCode { get; set; }
        public string OrderCodeDescription { get; set; }
        public Nullable<decimal> OrderCodePerDiemRate { get; set; }
        public Nullable<decimal> OrderCodeAddOns { get; set; }
        public string OrderCodeAddOnTableNumber { get; set; }
    }
}
