//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCRulesTable
    {
        [Key]
        public int ManagedCareRuleId { get; set; }
        public Nullable<int> RuleSetNumber { get; set; }
        public Nullable<int> RuleNumber { get; set; }
        public Nullable<int> AppliestoPatientType { get; set; }
        public Nullable<int> ConStart { get; set; }
        public Nullable<int> Calculation { get; set; }
        public Nullable<int> ConNextLine { get; set; }
        public string LHSTableName { get; set; }
        public string LHSTableColumn { get; set; }
        public string LHSTableKeyColumn { get; set; }
        public string DirectValue { get; set; }
        public Nullable<int> CalculationMethod { get; set; }
        public Nullable<decimal> CalcualtionRate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ConGroup { get; set; }
        public string RHSTableName { get; set; }
        public string RHSTableColumn { get; set; }
        public string RHSTableKeyColumn { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
    }
}
