//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenOrderActivitySchedule
    {
        [Key]
        public int OpenOrderActivityScheduleID { get; set; }
        public Nullable<int> OpenOrderID { get; set; }
        public Nullable<System.DateTime> ActivitySchecduleOn { get; set; }
        public Nullable<int> ActivityCompletedBy { get; set; }
        public Nullable<int> ActivityStatus { get; set; }
        public string OrderType { get; set; }
        public string OrderCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string ItemName { get; set; }
        public string ItemStrength { get; set; }
        public string ItemDosage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Comments { get; set; }
    }
}
