//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenOrder
    {
        [Key]
        public int OpenOrderID { get; set; }
        public Nullable<System.DateTime> OpenOrderPrescribedDate { get; set; }
        public Nullable<int> PhysicianID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> EncounterID { get; set; }
        public string DiagnosisCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string OrderType { get; set; }
        public string OrderCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string FrequencyCode { get; set; }
        public string PeriodDays { get; set; }
        public string OrderNotes { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<bool> IsActivitySchecduled { get; set; }
        public Nullable<System.DateTime> ActivitySchecduledOn { get; set; }
        public string ItemName { get; set; }
        public string ItemStrength { get; set; }
        public string ItemDosage { get; set; }
        public bool? IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CorporateID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string EV1 { get; set; }
        public string EV2 { get; set; }
        public string EV3 { get; set; }
        public string EV4 { get; set; }
    }
}
