//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfoChangesQueue
    {
        [Key]
        public int Id { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string GlobalCodeValue { get; set; }
        public string GlobalCodeCategory { get; set; }
        public string Status { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> CorporatId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
    }
}
