//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class PatientPhone
    {
        [Key]
        public int PatientPhoneId { get; set; }
        public int PatientID { get; set; }
        public int PhoneType { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsdontContact { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> PatientAddressRelationID { get; set; }

        [ScriptIgnoreAttribute]
        public virtual PatientInfo PatientInfo { get; set; }
    }
}