//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLoginDetail
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Email { get; set; }
        public string TokenId { get; set; }
        public bool PatientPortalAccess { get; set; }
        public string Password { get; set; }
        public string CodeValue { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LastInvalidLogin { get; set; }
        public Nullable<System.DateTime> LastResetPassword { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }

        public string Latitude { get; set; }
        public string Longitude { get; set; }

    }
}
