//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Physician
    {
        [Key]
        public int Id { get; set; }
        public Nullable<decimal> PhysicianEmployeeNumber { get; set; }
        public string PhysicianName { get; set; }
        public string PhysicianLicenseNumber { get; set; }
        public Nullable<int> PhysicianLicenseType { get; set; }
        public Nullable<System.DateTime> PhysicianLicenseEffectiveStartDate { get; set; }
        public Nullable<System.DateTime> PhysicianLicenseEffectiveEndDate { get; set; }
        public Nullable<int> PhysicianPrimaryFacility { get; set; }
        public Nullable<int> PhysicianSecondaryFacility { get; set; }
        public Nullable<int> PhysicianThirdFacility { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FacultySpeciality { get; set; }
        public string FacultyDepartment { get; set; }
        public string FacultyLunchTimeFrom { get; set; }
        public string FacultyLunchTimeTill { get; set; }
        public string ExtValue1 { get; set; }
        public string ExtValue2 { get; set; }
        public int CorporateId { get; set; }
        public int FacilityId { get; set; }
        public string AssociatedFacilities { get; set; }
        public bool IsSchedulingPublic { get; set; }
    }
}
