//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDashboard
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string JanTarget { get; set; }
        public string FebTarget { get; set; }
        public string MarTarget { get; set; }
        public string AprTarget { get; set; }
        public string MayTarget { get; set; }
        public string JunTarget { get; set; }
        public string JulTarget { get; set; }
        public string AugTarget { get; set; }
        public string SepTarget { get; set; }
        public string OctTarget { get; set; }
        public string NovTarget { get; set; }
        public string DecTarget { get; set; }
        public string ExternalValue1 { get; set; }
        public string ExternalValue2 { get; set; }
        public string ExternalValue3 { get; set; }
        public string ExternalValue4 { get; set; }
        public string ExternalValue5 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
