//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Scheduling
    {

        [Key]
        public int SchedulingId { get; set; }

        public int? AssociatedId { get; set; }

        public string AssociatedType { get; set; }

        public string SchedulingType { get; set; }

        public string Status { get; set; }

        public string StatusType { get; set; }

        public DateTime? ScheduleFrom { get; set; }

        public DateTime? ScheduleTo { get; set; }

        public string TypeOfVisit { get; set; }

        public string PhysicianSpeciality { get; set; }

        public string PhysicianId { get; set; }

        public string TypeOfProcedure { get; set; }

        public int? FacilityId { get; set; }

        public int? CorporateId { get; set; }

        public string Comments { get; set; }

        public string Location { get; set; }

        public int? CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public int? ModifiedBy { get; set; }

        public DateTime? ModifiedDate { get; set; }

        public bool? IsActive { get; set; }

        public int? DeletedBy { get; set; }

        public DateTime? DeletedDate { get; set; }

        public string ExtValue1 { get; set; }

        public string ExtValue2 { get; set; }

        public string ExtValue3 { get; set; }

        public string ExtValue4 { get; set; }

        public string ExtValue5 { get; set; }

        public bool? IsRecurring { get; set; }

        public string RecType { get; set; }

        public string RecPattern { get; set; }

        public long? RecEventlength { get; set; }

        public long? RecEventPId { get; set; }

        public DateTime? RecurringDateFrom { get; set; }

        public DateTime? RecurringDateTill { get; set; }

        public string EventId { get; set; }

        public string WeekDay { get; set; }

        public string EventParentId { get; set; }

        public int? RoomAssigned { get; set; }

        public int? EquipmentAssigned { get; set; }

        public long? PhysicianReferredBy { get; set; }

        //public string GoogleEventId { get; set; }
        //[Key]
        //public int SchedulingId { get; set; }
        //public int? PatientId { get; set; }
        //public int? EncounterId { get; set; }
        //public DateTime? ScheduleFrom { get; set; }
        //public DateTime? ScheduleTo { get; set; }
        //public int? PhysicianId { get; set; }
        //public string TypeOfVisit { get; set; }
        //public DateTime? ScheduleDate { get; set; }
        //public string PhysicianSpeciality { get; set; }
        //public string TypeOfProcedure { get; set; }
        //public int? FacilityId { get; set; }
        //public int? CorporateId { get; set; }
        //public string Comments { get; set; }
        //public string Location { get; set; }
        //public string ConfirmedByPatient { get; set; }
        //public string ApprovedByFacility { get; set; }
        //public string ExtValue1 { get; set; }
        //public string ExtValue2 { get; set; }
        //public string ExtValue3 { get; set; }
        //public string ExtValue4 { get; set; }
        //public string ExtValue5 { get; set; }
        //public bool? IsRecurring { get; set; }
        //public string RecType { get; set; }
        //public string RecPattern { get; set; }
        //public long? RecEventlength { get; set; }
        //public int? RecEventPId { get; set; }
        //public DateTime? RecurringDateFrom { get; set; }
        //public DateTime? RecurringDateTill { get; set; }
        //public string EventId { get; set; }
        //public string WeekDay { get; set; }
    }
}
