//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Screen
    {
        public Screen()
        {
            this.Tabs = new HashSet<Tabs>();
        }
        [Key]
        public int ScreenId { get; set; }
        public string ScreenTitle { get; set; }
        public string ScreenURL { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TabID { get; set; }
        public string ScreenMode { get; set; }
        public Nullable<int> GlobalCodeID { get; set; }
        public Nullable<bool> DefaultPermission { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ScreenGroup { get; set; }

        public virtual ICollection<Tabs> Tabs { get; set; }
    }
}
