//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCode
    {
        [Key]
        public int ServiceCodeId { get; set; }
        public string ServiceCodeTableNumber { get; set; }
        public string ServiceCodeTableDescription { get; set; }
        public string ServiceCodeValue { get; set; }
        public string ServiceCodeDescription { get; set; }
        public Nullable<int> ServiceCodePrice { get; set; }
        public Nullable<System.DateTime> ServiceCodeEffectiveDate { get; set; }
        public Nullable<System.DateTime> ServiceExpiryDate { get; set; }
        public string ServiceCodeBasicApplicationRule { get; set; }
        public string ServiceCodeOtherApplicationRule { get; set; }
        public string ServiceCodeServiceCodeMain { get; set; }
        public string ServiceServiceCodeSub { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CanOverRide { get; set; }
    }
}
