//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class Tabs
    {
        public Tabs()
        {
            this.RoleTabs = new HashSet<RoleTabs>();
        }
        [Key]
        public int TabId { get; set; }
        public string TabName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string RouteValues { get; set; }
        public Nullable<int> TabOrder { get; set; }
        public string TabImageUrl { get; set; }
        public int ParentTabId { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public bool IsDeleted { get; set; }
        public int ScreenID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string TabHierarchy { get; set; }


        public virtual ICollection<RoleTabs> RoleTabs { get; set; }
        [ScriptIgnoreAttribute]
        public virtual Screen Screen { get; set; }
    }
}
