//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTLOG
    {
        [Key]
        public int TESTID { get; set; }
        public Nullable<int> CorporateID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> EncounterID { get; set; }
        public Nullable<int> BillHeaderID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LHSValue { get; set; }
        public string RHSValue { get; set; }
        public string FreeTextValue { get; set; }
    }
}
