//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;

    public class Users
    {
        //public Users()
        //{
        //    this.AuditLog = new HashSet<AuditLog>();
        //    this.ModuleStepTracking = new HashSet<ModuleStepTracking>();
        //    this.UserRole = new HashSet<UserRole>();
        //}

        public Users()
        {
            this.UserRole = new HashSet<UserRole>();
        }

        [Key]
        public int UserID { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> UserGroup { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Answer { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string HomePhone { get; set; }
        public Nullable<bool> AdminUser { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LastInvalidLogin { get; set; }
        public Nullable<System.DateTime> LastResetPassword { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        //public Nullable<int> UserType { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string UserToken { get; set; }
        public Nullable<System.DateTime> TokenExpiryDate { get; set; }
        public string ResetToken { get; set; }

        //public virtual ICollection<AuditLog> AuditLog { get; set; }
        //public virtual ICollection<ModuleStepTracking> ModuleStepTracking { get; set; }

        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
