//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XActivity
    {
        [Key]
        public long XActivity1 { get; set; }
        public long EncounterID { get; set; }
        public long ActivityID { get; set; }
        public string DType { get; set; }
        public string DCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string AType { get; set; }
        public string ACode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string OrderingClinician { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Clinician { get; set; }
        public Nullable<System.DateTime> OrderCloseDate { get; set; }
        public string PriorAuthorizationID { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> PatientShare { get; set; }
        public Nullable<decimal> Net { get; set; }
        public string DenialCode { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<System.DateTime> DateSettlement { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PatientPayReference { get; set; }
        public Nullable<System.DateTime> PatientDateSettlement { get; set; }
        public Nullable<decimal> PatientPayAmount { get; set; }
        public string Status { get; set; }
        public Nullable<long> ClaimID { get; set; }
        public Nullable<long> FileID { get; set; }
        public Nullable<long> ARFileID { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> MCDiscount { get; set; }
    }
}
