//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAdviceXMLParsedData
    {
        [Key]
        public long XAdviceXMLParsedDataID { get; set; }
        public Nullable<long> XAFileHeaderFileID { get; set; }
        public string XACClaimID { get; set; }
        public string XACIDPayer { get; set; }
        public string XACProviderID { get; set; }
        public string XACDenialCode { get; set; }
        public string XACPaymentReference { get; set; }
        public string XACDateSettlement { get; set; }
        public string XAEFacilityID { get; set; }
        public string XAAActivityID { get; set; }
        public string XAAStart { get; set; }
        public string XAAType { get; set; }
        public string XAACode { get; set; }
        public string XAAQuantity { get; set; }
        public string XAANet { get; set; }
        public string XAAOrderingClinician { get; set; }
        public string XAAPriorAuthorizationID { get; set; }
        public string XAAGross { get; set; }
        public string XAAPatientShare { get; set; }
        public string XAAPaymentAmount { get; set; }
        public string XAADenialCode { get; set; }
        public string XAModifiedBy { get; set; }
        public Nullable<System.DateTime> XAModifiedDate { get; set; }
        public Nullable<int> XAAdviceStatus { get; set; }
        public Nullable<int> CorporateID { get; set; }
        public Nullable<int> FacilityID { get; set; }
    }
}
