//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class XFileXML
    {


        [Key]
        public long FileXMLID { get; set; }
        [Column("XFileXML")]
        public string XFileXML1 { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
