//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BillingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XPaymentReturn
    {
        [Key]
        public long XPaymentReturnID { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public string DispositionFlag { get; set; }
        public Nullable<int> ID { get; set; }
        public string IDPayer { get; set; }
        public string ProviderID { get; set; }
        public string DenialCode { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<System.DateTime> DateSettlement { get; set; }
        public string FacilityID { get; set; }
        public Nullable<int> AActivityID { get; set; }
        public Nullable<System.DateTime> AStart { get; set; }
        public string AType { get; set; }
        public string ACode { get; set; }
        public Nullable<int> AQuantity { get; set; }
        public Nullable<decimal> AANet { get; set; }
        public string AAOrderingClinician { get; set; }
        public string AAPriorAuthorizationID { get; set; }
        public Nullable<decimal> AAGross { get; set; }
        public Nullable<decimal> AAPatientShare { get; set; }
        public Nullable<decimal> AAPaymentAmount { get; set; }
        public string AADenialCode { get; set; }
        public string XModifiedBy { get; set; }
        public Nullable<System.DateTime> XModifiedDate { get; set; }
        public Nullable<int> AdviceStatus { get; set; }
        public Nullable<int> XCorporateID { get; set; }
        public Nullable<int> XFacilityID { get; set; }
    }
}
