//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace BillingSystem.Model.CustomModel
{
    [NotMapped]
    public class RoleTabsCustomModel
    {
        public int ID { get; set; }
        public int? RoleID { get; set; }
        public int? TabID { get; set; }
    }
}
